spring.application.name=libriflow

## H2 em memória - dados somem ao reiniciar
#spring.datasource.url=jdbc:h2:mem:libriflow;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create-drop
## Mostra todas as queries no log - excelente para ver o N+1 em ação
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# --- Configuração do Banco de Dados (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/libriflow_db
spring.datasource.username=libriflow_user
spring.datasource.password=libriflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# --- Configuração do Hibernate / JPA ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.port=8080
spring.cloud.openfeign.circuitbreaker.enabled=true
