spring.application.name=book-service
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/libriflow_db?currentSchema=catalog
spring.datasource.username=libriflow_user
spring.datasource.password=libriflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.sql.init.mode=always