spring.application.name=user-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5433/libriflow_db?currentSchema=auth
spring.datasource.username=libriflow_user
spring.datasource.password=libriflow_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=auth
spring.jpa.show-sql=true

# Força a criação do Schema se ele não existir
spring.jpa.properties.hibernate.hbm2ddl.create_namespaces=true
spring.sql.init.mode=always